apiVersion: v1
kind: ConfigMap
metadata:
  name: taskmanager-config
  namespace: default
data:
  APP_PORT: "8080"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "taskmanager"
  DB_USER: "postgres"
  JWT_EXPIRY_HOURS: "24"